### ISSUE TITLE
Error: You passed more items (**) than blocks in this instance (**)

### ISSUE THREAD

**Issue by eng-luciano-julien** [ThatOpen/engine_components#275]
### Describe the bug 📝

I am using openbim-backend-components for backend processing, but I reproduced the bug also in the browser with openbim-components on the demo https://platform.thatopen.com/app.
I have two files with the same error, one of 143MB and one of 115MB.
I can share the files privately.

### Reproduction ▶️

https://platform.thatopen.com/app

### Steps to reproduce 🔢

1. Go to https://platform.thatopen.com/app
2. Open the model
3. The error appears in the log

### System Info 💻

```shell
Windows, Microsoft Edge
```

### Used Package Manager 📦

npm

### Error Trace/Logs 📃

<details>
<summary>Click to expand!</summary>

```shell
Uncaught (in promise) Error: You passed more items (92582) than blocks in this instance (65536)
    at Fragment.checkBlockNumberValid (openbim-components.js:19947:19)
    at Fragment.saveItemsInMap (openbim-components.js:19919:14)
    at Fragment.setInstance (openbim-components.js:19827:18)
    at DataConverter.createAllFragments (openbim-components.js:100706:22)
    at DataConverter.generate (openbim-components.js:100479:14)
    at async FragmentIfcLoader.load (openbim-components.js:100930:23)
    at async fileOpener.onchange (openbim-components.js:100975:31)
```
</details>

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by eng-luciano-julien** [comment]
Solved on new version.
